//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoIt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoIt.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageAbout {
            get {
                return ResourceManager.GetString("AboutPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string AboutPageDesign {
            get {
                return ResourceManager.GetString("AboutPageDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect account.
        /// </summary>
        public static string AboutPageDisconnectAccount {
            get {
                return ResourceManager.GetString("AboutPageDisconnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to microsoft account.
        /// </summary>
        public static string AboutPageDisconnectHeader {
            get {
                return ResourceManager.GetString("AboutPageDisconnectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string AboutPageFirstName {
            get {
                return ResourceManager.GetString("AboutPageFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string AboutPageGraphics {
            get {
                return ResourceManager.GetString("AboutPageGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        public static string AboutPageLastName {
            get {
                return ResourceManager.GetString("AboutPageLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is too long or to short, please enter another first name..
        /// </summary>
        public static string AboutPageNameWarning {
            get {
                return ResourceManager.GetString("AboutPageNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid name.
        /// </summary>
        public static string AboutPageNameWarningTitle {
            get {
                return ResourceManager.GetString("AboutPageNameWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only change your name while connected to the internet..
        /// </summary>
        public static string AboutPageNoConnection {
            get {
                return ResourceManager.GetString("AboutPageNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push notifications.
        /// </summary>
        public static string AboutPageNotifications {
            get {
                return ResourceManager.GetString("AboutPageNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string AboutPageProgramming {
            get {
                return ResourceManager.GetString("AboutPageProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AboutPageSettings {
            get {
                return ResourceManager.GetString("AboutPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support mail.
        /// </summary>
        public static string AboutPageSupportMail {
            get {
                return ResourceManager.GetString("AboutPageSupportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///I am using {0} version {1} and I have a question or an idea for future versions:
        ///
        ///
        ///
        ///
        ///
        ///Many thanks!
        ///Kind Regards..
        /// </summary>
        public static string AboutPageSupportMailBody {
            get {
                return ResourceManager.GetString("AboutPageSupportMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Questions and Ideas.
        /// </summary>
        public static string AboutPageSupportMailSubject {
            get {
                return ResourceManager.GetString("AboutPageSupportMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        public static string AlphabeticalOrder {
            get {
                return ResourceManager.GetString("AlphabeticalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading offline data. A backup of the last time you were logged in will be restored the next time a data connection is available..
        /// </summary>
        public static string AppErrorLoading {
            get {
                return ResourceManager.GetString("AppErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about and settings.
        /// </summary>
        public static string ApplicationBarAbout {
            get {
                return ResourceManager.GetString("ApplicationBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string ApplicationBarAdd {
            get {
                return ResourceManager.GetString("ApplicationBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect account.
        /// </summary>
        public static string ApplicationBarDisconnectAccount {
            get {
                return ResourceManager.GetString("ApplicationBarDisconnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find friend.
        /// </summary>
        public static string ApplicationBarFindFriend {
            get {
                return ResourceManager.GetString("ApplicationBarFindFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished tasks.
        /// </summary>
        public static string ApplicationBarFinishedTasks {
            get {
                return ResourceManager.GetString("ApplicationBarFinishedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ApplicationBarRemove {
            get {
                return ResourceManager.GetString("ApplicationBarRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove ads and more.
        /// </summary>
        public static string ApplicationBarRemoveAds {
            get {
                return ResourceManager.GetString("ApplicationBarRemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove friend.
        /// </summary>
        public static string ApplicationBarRemoveFriend {
            get {
                return ResourceManager.GetString("ApplicationBarRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove {0} from your friends?.
        /// </summary>
        public static string ApplicationBarRemoveFriendMessage {
            get {
                return ResourceManager.GetString("ApplicationBarRemoveFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove friend?.
        /// </summary>
        public static string ApplicationBarRemoveFriendMessageTitle {
            get {
                return ResourceManager.GetString("ApplicationBarRemoveFriendMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do it.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO IT.
        /// </summary>
        public static string ApplicationTitleUpperCase {
            get {
                return ResourceManager.GetString("ApplicationTitleUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string CustomDateToTextConverterCustom {
            get {
                return ResourceManager.GetString("CustomDateToTextConverterCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some day.
        /// </summary>
        public static string CustomDateToTextConverterFuture {
            get {
                return ResourceManager.GetString("CustomDateToTextConverterFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as soon as possible.
        /// </summary>
        public static string CustomDateToTextConverterSoon {
            get {
                return ResourceManager.GetString("CustomDateToTextConverterSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started
        ///Enter your tasks in do it and receive points for finishing them..
        /// </summary>
        public static string DataNewCreatedTask1 {
            get {
                return ResourceManager.GetString("DataNewCreatedTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Points
        ///Receive bonus points for finishing tasks on time. Tasks from friends yield more points, finishing tasks late yields less points..
        /// </summary>
        public static string DataNewCreatedTask2 {
            get {
                return ResourceManager.GetString("DataNewCreatedTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note
        ///It&apos;s easy to cheat do it to get more points. Keep in mind, cheating your to do list means cheating yourself..
        /// </summary>
        public static string DataNewCreatedTask3 {
            get {
                return ResourceManager.GetString("DataNewCreatedTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong. You can help us fix the problem as soon as possible by mailing us an error report. Send an error report now?.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send error report?.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///I am using {0} version {1} and the error {2} occurred:
        ///{3}
        ///A short description from me:
        ///
        ///
        ///
        ///
        ///Additional information:
        ///{4}
        ///Navigation:
        ///{5}
        ///
        ///Kind Regards..
        /// </summary>
        public static string ErrorReportBody {
            get {
                return ResourceManager.GetString("ErrorReportBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Error report.
        /// </summary>
        public static string ErrorReportSubject {
            get {
                return ResourceManager.GetString("ErrorReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No finished tasks... yet?.
        /// </summary>
        public static string FinishedTaskPageEmtpyString {
            get {
                return ResourceManager.GetString("FinishedTaskPageEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished tasks.
        /// </summary>
        public static string FinishedTaskPageTitle {
            get {
                return ResourceManager.GetString("FinishedTaskPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using do it since.
        /// </summary>
        public static string FriendDetailPageAccountCreatedDate {
            get {
                return ResourceManager.GetString("FriendDetailPageAccountCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score per day.
        /// </summary>
        public static string FriendDetailPageAverageScore {
            get {
                return ResourceManager.GetString("FriendDetailPageAverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string FriendDetailPageCountry {
            get {
                return ResourceManager.GetString("FriendDetailPageCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the selected person..
        /// </summary>
        public static string FriendDetailPageNotFound {
            get {
                return ResourceManager.GetString("FriendDetailPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        public static string FriendDetailPageScore {
            get {
                return ResourceManager.GetString("FriendDetailPageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string FriendDetailPageUnknownCountry {
            get {
                return ResourceManager.GetString("FriendDetailPageUnknownCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload all your offline tasks? Pressing cancel will delete all your offline tasks and reset your offline score..
        /// </summary>
        public static string LogInBoxMessage {
            get {
                return ResourceManager.GetString("LogInBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload data?.
        /// </summary>
        public static string LogInBoxMessageTitle {
            get {
                return ResourceManager.GetString("LogInBoxMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do it will notify you about friend requests, when friends assign tasks to you or modify tasks assigned to you. Do you want to enable notifications?.
        /// </summary>
        public static string LogInBoxNotificationWarning {
            get {
                return ResourceManager.GetString("LogInBoxNotificationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow notifications?.
        /// </summary>
        public static string LogInBoxNotificationWarningTitle {
            get {
                return ResourceManager.GetString("LogInBoxNotificationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add {0} as a friend?.
        /// </summary>
        public static string MainPageAddFriendMessage {
            get {
                return ResourceManager.GetString("MainPageAddFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend?.
        /// </summary>
        public static string MainPageAddFriendMessageTitle {
            get {
                return ResourceManager.GetString("MainPageAddFriendMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Microsoft Account.
        /// </summary>
        public static string MainPageButtonMicrosoftAccount {
            get {
                return ResourceManager.GetString("MainPageButtonMicrosoftAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my current score.
        /// </summary>
        public static string MainPageCurrentScore {
            get {
                return ResourceManager.GetString("MainPageCurrentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting the app from your account makes working with your friends impossible. Do you really want to disconnect from your account?.
        /// </summary>
        public static string MainPageDisconnectAccountMessage {
            get {
                return ResourceManager.GetString("MainPageDisconnectAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Account.
        /// </summary>
        public static string MainPageDisconnectAccountMessageTitle {
            get {
                return ResourceManager.GetString("MainPageDisconnectAccountMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string MainPageFriends {
            get {
                return ResourceManager.GetString("MainPageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to online friend list..
        /// </summary>
        public static string MainPageFriendsEmtpyString {
            get {
                return ResourceManager.GetString("MainPageFriendsEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to future.
        /// </summary>
        public static string MainPageFuture {
            get {
                return ResourceManager.GetString("MainPageFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in. Is the data connection working?.
        /// </summary>
        public static string MainPageLoginError {
            get {
                return ResourceManager.GetString("MainPageLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to work together with friends, assign tasks to them and compete for the highest productivity score..
        /// </summary>
        public static string MainPageLoginText {
            get {
                return ResourceManager.GetString("MainPageLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in....
        /// </summary>
        public static string MainPageProgressIndicatorLoggingIn {
            get {
                return ResourceManager.GetString("MainPageProgressIndicatorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncing....
        /// </summary>
        public static string MainPageProgressIndicatorSyncing {
            get {
                return ResourceManager.GetString("MainPageProgressIndicatorSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading data....
        /// </summary>
        public static string MainPageProgressIndicatorUploading {
            get {
                return ResourceManager.GetString("MainPageProgressIndicatorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requests.
        /// </summary>
        public static string MainPageRequests {
            get {
                return ResourceManager.GetString("MainPageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string MainPageTaskGroupLater {
            get {
                return ResourceManager.GetString("MainPageTaskGroupLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MainPageTaskGroupMonth {
            get {
                return ResourceManager.GetString("MainPageTaskGroupMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string MainPageTaskGroupOverdue {
            get {
                return ResourceManager.GetString("MainPageTaskGroupOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string MainPageTaskGroupThreeDays {
            get {
                return ResourceManager.GetString("MainPageTaskGroupThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string MainPageTaskGroupToday {
            get {
                return ResourceManager.GetString("MainPageTaskGroupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string MainPageTaskGroupTomorrow {
            get {
                return ResourceManager.GetString("MainPageTaskGroupTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string MainPageTaskGroupWeek {
            get {
                return ResourceManager.GetString("MainPageTaskGroupWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string MainPageToday {
            get {
                return ResourceManager.GetString("MainPageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do today. Yay! Maybe do some of your future tasks?.
        /// </summary>
        public static string MainPageTodayEmtpyString {
            get {
                return ResourceManager.GetString("MainPageTodayEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do. Tap + to add tasks..
        /// </summary>
        public static string MainPageTommorowEmtpyString {
            get {
                return ResourceManager.GetString("MainPageTommorowEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string PersonFullName {
            get {
                return ResourceManager.GetString("PersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PersonUnknownFirstName {
            get {
                return ResourceManager.GetString("PersonUnknownFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string PersonUnknownLastName {
            get {
                return ResourceManager.GetString("PersonUnknownLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send a friend request to {0}?.
        /// </summary>
        public static string SearchFriendsPageAddMessage {
            get {
                return ResourceManager.GetString("SearchFriendsPageAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend?.
        /// </summary>
        public static string SearchFriendsPageAddMessageTitle {
            get {
                return ResourceManager.GetString("SearchFriendsPageAddMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching....
        /// </summary>
        public static string SearchFriendsPageProgressIndicatorSearching {
            get {
                return ResourceManager.GetString("SearchFriendsPageProgressIndicatorSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request successfully sent..
        /// </summary>
        public static string SearchFriendsPageSuccessMessage {
            get {
                return ResourceManager.GetString("SearchFriendsPageSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friends.
        /// </summary>
        public static string SearchFriendsPageTitle {
            get {
                return ResourceManager.GetString("SearchFriendsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string TaskNewDescription {
            get {
                return ResourceManager.GetString("TaskNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} early bonus.
        /// </summary>
        public static string TaskPageBonusScoreEarly {
            get {
                return ResourceManager.GetString("TaskPageBonusScoreEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} not on time.
        /// </summary>
        public static string TaskPageBonusScoreLate {
            get {
                return ResourceManager.GetString("TaskPageBonusScoreLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on time.
        /// </summary>
        public static string TaskPageBonusScoreOnTime {
            get {
                return ResourceManager.GetString("TaskPageBonusScoreOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by.
        /// </summary>
        public static string TaskPageCreatedBy {
            get {
                return ResourceManager.GetString("TaskPageCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string TaskPageDate {
            get {
                return ResourceManager.GetString("TaskPageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date and time.
        /// </summary>
        public static string TaskPageDateTime {
            get {
                return ResourceManager.GetString("TaskPageDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string TaskPageDescription {
            get {
                return ResourceManager.GetString("TaskPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ done.
        /// </summary>
        public static string TaskPageDone {
            get {
                return ResourceManager.GetString("TaskPageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string TaskPageFriends {
            get {
                return ResourceManager.GetString("TaskPageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends here? Add some people you know on the main page!.
        /// </summary>
        public static string TaskPageFriendsEmtpyString {
            get {
                return ResourceManager.GetString("TaskPageFriendsEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading list of assigned friends failed..
        /// </summary>
        public static string TaskPageFriendsEmtpyStringNotUserCreated {
            get {
                return ResourceManager.GetString("TaskPageFriendsEmtpyStringNotUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string TaskPageHeaderAdd {
            get {
                return ResourceManager.GetString("TaskPageHeaderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string TaskPageHeaderEdit {
            get {
                return ResourceManager.GetString("TaskPageHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tasks does not seem to exist anymore..
        /// </summary>
        public static string TaskPageNotFoundMessage {
            get {
                return ResourceManager.GetString("TaskPageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading task....
        /// </summary>
        public static string TaskPageProgressIndicatorLoadingTask {
            get {
                return ResourceManager.GetString("TaskPageProgressIndicatorLoadingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminders.
        /// </summary>
        public static string TaskPageReminders {
            get {
                return ResourceManager.GetString("TaskPageReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this task?.
        /// </summary>
        public static string TaskPageRemoveMessage {
            get {
                return ResourceManager.GetString("TaskPageRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove task?.
        /// </summary>
        public static string TaskPageRemoveMessageTitle {
            get {
                return ResourceManager.GetString("TaskPageRemoveMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskPageTask {
            get {
                return ResourceManager.GetString("TaskPageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time:.
        /// </summary>
        public static string TaskPageTime {
            get {
                return ResourceManager.GetString("TaskPageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do it - Task.
        /// </summary>
        public static string TaskReminderHeader {
            get {
                return ResourceManager.GetString("TaskReminderHeader", resourceCulture);
            }
        }
    }
}
